import type { LetterDef } from './types'

export const DEFAULT_LETTERS: Record<string, LetterDef> = {
	A: {
		components: [
			{
				type: 'arc',
				start: -150,
				end: 150,
				order: 0,
				animate: [{ preset: 'draw', duration: 800, easing: 'ease-in-out', reverse: true }],
			},
			{
				type: 'line',
				angle: 90,
				fromCenter: true,
				reach: 1,
				order: 2,
				animate: [{ preset: 'draw', duration: 200, easing: 'ease-out' }],
			},
			{
				type: 'line',
				angle: 270,
				fromCenter: false,
				reach: 1,
				order: 1,
				animate: [{ preset: 'draw', duration: 200, easing: 'ease-out' }],
			},
		],
	},
	B: {
		components: [
			{
				type: 'arc',
				start: -90,
				end: 45,
				order: 0,
				animate: [{ preset: 'draw', duration: 600, easing: 'ease-in-out' }],
			},
			{
				type: 'arc',
				start: 135,
				end: -90,
				order: 0,
				animate: [{ preset: 'draw', duration: 600, easing: 'ease-in-out' }],
			},
			/* {
				type: 'edge',
				position: 'tr',
				orientation: 'h',
				order: 0,
				animate: [{ preset: 'draw', duration: 600, easing: 'ease-in-out' }],
			}, */
			{
				type: 'arc',
				start: 90,
				end: 180,
				offset: [0, -112],
				mask: true,
				order: 0,
				animate: [{ preset: 'draw', duration: 600, easing: 'ease-in-out' }],
			},
			/* {
				type: 'edge',
				position: 'br',
				orientation: 'h',
				order: 0,
				animate: [{ preset: 'draw', duration: 600, easing: 'ease-in-out' }],
			}, */
			{
				type: 'arc',
				start: 0,
				end: 90,
				offset: [0, 112],
				mask: true,
				order: 0,
				animate: [{ preset: 'draw', duration: 600, easing: 'ease-in-out' }],
			},
			// {
			// 	type: 'line',
			// 	angle: 80,
			// 	fromCenter: true,
			// 	order: 1,
			// 	animate: [{ preset: 'draw', duration: 350, easing: 'ease-out' }],
			// },
			// {
			// 	type: 'line',
			// 	angle: 100,
			// 	fromCenter: true,
			// 	order: 1,
			// 	animate: [{ preset: 'draw', duration: 350, easing: 'ease-out' }],
			// },
			{
				type: 'line',
				angle: -90,
				fromCenter: true,
				order: 1,
				animate: [{ preset: 'draw', duration: 350, easing: 'ease-out' }],
			},
		],
	},
	C: {
		components: [
			{
				type: 'arc',
				start: 135,
				end: 45,
				order: 0,
				animate: [{ preset: 'draw', duration: 800, easing: 'ease-in-out' }],
			},
		],
	},
	D: {
		components: [
			{
				type: 'arc',
				start: -30,
				end: 210,
				order: 0,
				animate: [{ preset: 'draw', duration: 800, easing: 'ease-in-out' }],
			},
		],
	},
	E: {
		components: [
			{
				type: 'arc',
				start: 150,
				end: 30,
				order: 0,
				animate: [{ preset: 'draw', duration: 700, easing: 'ease-in-out' }],
			},
			{
				type: 'line',
				angle: -90,
				fromCenter: false,
				order: 1,
				animate: [{ preset: 'draw', duration: 400, easing: 'ease-out' }],
			},
			{
				type: 'line',
				angle: 90,
				fromCenter: true,
				reach: 0.6,
				order: 2,
				animate: [{ preset: 'draw', duration: 400, easing: 'ease-out' }],
			},
		],
	},
	F: {
		components: [
			{
				type: 'arc',
				start: 210,
				end: 25,
				order: 0,
				animate: [{ preset: 'draw', duration: 700, easing: 'ease-in-out' }],
			},
			{
				type: 'line',
				angle: -90,
				fromCenter: false,
				order: 1,
				animate: [{ preset: 'draw', duration: 400, easing: 'ease-out' }],
			},
			{
				type: 'line',
				angle: 90,
				fromCenter: true,
				reach: 0.6,
				order: 2,
				animate: [{ preset: 'draw', duration: 400, easing: 'ease-out' }],
			},
		],
	},
	G: {
		components: [
			{
				type: 'arc',
				start: 90,
				end: 0,
				order: 0,
				animate: [{ preset: 'draw', duration: 500, easing: 'ease-out', reverse: true }],
			},
			{
				type: 'line',
				angle: 90,
				reach: 1,
				order: 1,
				animate: [{ preset: 'draw', duration: 400, easing: 'ease-out' }],
			},
		],
	},
	H: {
		components: [
			{
				type: 'arc',
				start: 30,
				end: 150,
				order: 0,
				animate: [{ preset: 'draw', duration: 600, easing: 'ease-in-out' }],
			},
			{
				type: 'arc',
				start: 210,
				end: 330,
				order: 0,
				animate: [{ preset: 'draw', duration: 600, easing: 'ease-in-out' }],
			},
			{
				type: 'line',
				angle: 270,
				fromCenter: true,
				order: 1,
				animate: [{ preset: 'draw', duration: 400, easing: 'ease-out' }],
			},
			{
				type: 'line',
				angle: 90,
				fromCenter: true,
				order: 1,
				animate: [{ preset: 'draw', duration: 400, easing: 'ease-out' }],
			},
		],
	},
	I: {
		components: [
			{
				type: 'arc',
				start: 0,
				end: 20,
				order: 1,
				animate: [{ preset: 'draw', duration: 500, easing: 'ease-in-out' }],
			},
			{
				type: 'arc',
				start: -20,
				end: 0,
				order: 1,
				animate: [{ preset: 'draw', duration: 500, easing: 'ease-in-out', reverse: true }],
			},
			{
				type: 'arc',
				start: 180,
				end: 200,
				order: 1,
				animate: [{ preset: 'draw', duration: 500, easing: 'ease-in-out' }],
			},
			{
				type: 'arc',
				start: 160,
				end: 180,
				order: 1,
				animate: [{ preset: 'draw', duration: 500, easing: 'ease-in-out', reverse: true }],
			},
			{
				type: 'line',
				angle: 0,
				fromCenter: true,
				order: 0,
				animate: [{ preset: 'draw', duration: 350, easing: 'ease-out' }],
			},
			{
				type: 'line',
				angle: 180,
				fromCenter: true,
				order: 0,
				animate: [{ preset: 'draw', duration: 350, easing: 'ease-out' }],
			},
		],
	},
	J: {
		components: [
			{
				type: 'arc',
				start: 0,
				end: 270,
				order: 0,
				animate: [{ preset: 'draw', duration: 800, easing: 'ease-in-out' }],
			},
		],
	},
	K: {
		components: [
			{
				type: 'arc',
				start: -140,
				end: -40,
				order: 0,
				animate: [{ preset: 'draw', duration: 400, easing: 'ease-in-out', reverse: true }],
			},
			{
				type: 'line',
				angle: 40,
				fromCenter: true,
				reach: 1.1,
				order: 2,
				animate: [{ preset: 'draw', duration: 200, easing: 'ease-out' }],
			},
			{
				type: 'line',
				angle: 140,
				fromCenter: true,
				reach: 1.2,
				order: 3,
				animate: [{ preset: 'draw', duration: 200, easing: 'ease-out' }],
			},
			{
				type: 'line',
				angle: -140,
				fromCenter: false,
				order: 1,
				animate: [{ preset: 'draw', duration: 200, easing: 'ease-out' }],
			},
		],
	},
	L: {
		components: [
			{
				type: 'arc',
				start: 180,
				end: -45,
				order: 0,
				animate: [{ preset: 'draw', duration: 400, easing: 'ease-in-out', reverse: true }],
			},
			{
				type: 'edge',
				position: 'br',
				orientation: 'h',
				order: 1,
				reach: 0.5,
				fromCenter: true,
				animate: [{ preset: 'draw', duration: 400, easing: 'ease-out' }],
			},
		],
	},
	M: {
		components: [
			{
				type: 'arc',
				start: 35,
				end: 150,
				order: 0,
				animate: [{ preset: 'draw', duration: 600, easing: 'ease-in-out' }],
			},
			{
				type: 'arc',
				start: -150,
				end: -35,
				order: 0,
				animate: [{ preset: 'draw', duration: 600, easing: 'ease-in-out' }],
			},
			{
				type: 'line',
				angle: 35,
				fromCenter: true,
				order: 1,
				animate: [{ preset: 'draw', duration: 400, easing: 'ease-out' }],
			},
			{
				type: 'line',
				angle: -35,
				fromCenter: true,
				order: 1,
				animate: [{ preset: 'draw', duration: 400, easing: 'ease-out' }],
			},
		],
	},
	N: {
		components: [
			{
				type: 'arc',
				start: 30,
				end: 150,
				order: 0,
				animate: [{ preset: 'draw', duration: 600, easing: 'ease-in-out' }],
			},
			{
				type: 'arc',
				start: 210,
				end: 330,
				order: 0,
				animate: [{ preset: 'draw', duration: 600, easing: 'ease-in-out' }],
			},
			{
				type: 'line',
				angle: -30,
				fromCenter: true,
				order: 1,
				animate: [{ preset: 'draw', duration: 400, easing: 'ease-out' }],
			},
			{
				type: 'line',
				angle: 150,
				fromCenter: true,
				order: 1,
				animate: [{ preset: 'draw', duration: 400, easing: 'ease-out' }],
			},
		],
	},
	O: {
		components: [
			{
				type: 'arc',
				start: 0,
				end: 360,
				order: 0,
				animate: [{ preset: 'draw', duration: 1000, easing: 'ease-in-out' }],
			},
		],
	},
	P: {
		components: [
			/* {
				type: 'arc',
				start: -140,
				end: 0,
				order: 0,
				animate: [{ preset: 'draw', duration: 700, easing: 'ease-in-out' }],
			},
			{
				type: 'edge',
				position: 'tr',
				orientation: 'h',
				order: 0,
				animate: [{ preset: 'draw', duration: 600, easing: 'ease-in-out' }],
			},
			{
				type: 'arc',
				start: 90,
				end: 180,
				offset: [0, -112],
				order: 0,
				animate: [{ preset: 'draw', duration: 600, easing: 'ease-in-out' }],
			},
			{
				type: 'line',
				angle: -90,
				fromCenter: true,
				order: 2,
				animate: [{ preset: 'draw', duration: 400, easing: 'ease-out' }],
			}, */
			/* {
				type: 'edge',
				position: 'bl',
				orientation: 'v',
				order: 0,
				animate: [{ preset: 'draw', duration: 600, easing: 'ease-in-out' }],
			}, */
			{
				type: 'arc',
				start: -150,
				end: 90,
				order: 0,
				animate: [{ preset: 'draw', duration: 700, easing: 'ease-in-out' }],
			},
			{
				type: 'line',
				angle: 90,
				fromCenter: false,
				order: 1,
				animate: [{ preset: 'draw', duration: 400, easing: 'ease-out' }],
			},
			{
				type: 'line',
				angle: -90,
				fromCenter: true,
				order: 2,
				animate: [{ preset: 'draw', duration: 400, easing: 'ease-out' }],
			},
		],
	},
	Q: {
		components: [
			{
				type: 'arc',
				start: 0,
				end: 360,
				order: 0,
				animate: [{ preset: 'draw', duration: 800, easing: 'ease-in-out' }],
			},
			{
				type: 'line',
				angle: -135,
				fromCenter: true,
				reach: 1.4,
				order: 1,
				animate: [{ preset: 'draw', duration: 500, easing: 'ease-out' }],
			},
		],
	},
	R: {
		components: [
			{
				type: 'arc',
				start: -150,
				end: 90,
				order: 0,
				animate: [{ preset: 'draw', duration: 700, easing: 'ease-in-out' }],
			},
			{
				type: 'line',
				angle: 90,
				fromCenter: false,
				order: 1,
				animate: [{ preset: 'draw', duration: 400, easing: 'ease-out' }],
			},
			/* {
				type: 'arc',
				start: -140,
				end: 0,
				order: 0,
				animate: [{ preset: 'draw', duration: 700, easing: 'ease-in-out' }],
			},
			{
				type: 'edge',
				position: 'tr',
				orientation: 'h',
				order: 0,
				animate: [{ preset: 'draw', duration: 600, easing: 'ease-in-out' }],
			},
			{
				type: 'arc',
				start: 90,
				end: 180,
				offset: [0, -112],
				order: 0,
				animate: [{ preset: 'draw', duration: 600, easing: 'ease-in-out' }],
			}, */
			{
				type: 'line',
				angle: -90,
				fromCenter: true,
				order: 2,
				animate: [{ preset: 'draw', duration: 400, easing: 'ease-out' }],
			},
			{
				type: 'line',
				angle: 135,
				fromCenter: true,
				reach: 1.4,
				order: 3,
				animate: [{ preset: 'draw', duration: 400, easing: 'ease-out' }],
			},
		],
	},
	S: {
		components: [
			{
				type: 'arc',
				start: -50,
				end: 50,
				order: 4,
				animate: [{ preset: 'draw', duration: 600, easing: 'ease-in-out' }],
			},
			{
				type: 'arc',
				start: 130,
				end: 230,
				order: 3,
				animate: [{ preset: 'draw', duration: 600, easing: 'ease-in-out' }],
			},
			{
				type: 'line',
				angle: -50,
				fromCenter: false,
				order: 1,
				animate: [{ preset: 'draw', duration: 400, easing: 'ease-out' }],
			},
			{
				type: 'line',
				angle: -230,
				fromCenter: true,
				order: 2,
				animate: [{ preset: 'draw', duration: 400, easing: 'ease-out' }],
			},
		],
	},
	T: {
		components: [
			{
				type: 'arc',
				start: -70,
				end: 70,
				order: 0,
				animate: [{ preset: 'draw', duration: 700, easing: 'ease-in-out' }],
			},
			{
				type: 'line',
				angle: 0,
				fromCenter: true,
				order: 1,
				animate: [{ preset: 'draw', duration: 400, easing: 'ease-out' }],
			},
			{
				type: 'line',
				angle: 180,
				fromCenter: true,
				order: 1,
				animate: [{ preset: 'draw', duration: 400, easing: 'ease-out' }],
			},
		],
	},
	U: {
		components: [
			{
				type: 'arc',
				start: 45,
				end: -45,
				order: 0,
				animate: [{ preset: 'draw', duration: 700, easing: 'ease-in-out' }],
			},
			// {
			// 	type: 'edge',
			// 	position: 'tl',
			// 	orientation: 'v',
			// 	order: 1,
			// 	animate: [{ preset: 'draw', duration: 400, easing: 'ease-out', reverse: true }],
			// },
			// {
			// 	type: 'edge',
			// 	position: 'tr',
			// 	orientation: 'v',
			// 	order: 1,
			// 	animate: [{ preset: 'draw', duration: 400, easing: 'ease-out', reverse: true }],
			// },
		],
	},
	V: {
		components: [
			{
				type: 'arc',
				start: 45,
				end: 90,
				order: 0,
				animate: [{ preset: 'draw', duration: 700, easing: 'ease-in-out' }],
			},
			{
				type: 'arc',
				start: -90,
				end: -45,
				order: 0,
				animate: [{ preset: 'draw', duration: 700, easing: 'ease-in-out' }],
			},
			{
				type: 'diagonal',
				position: 'br',
				order: 2,
				animate: [{ preset: 'draw', duration: 350, easing: 'ease-out' }],
			},
			{
				type: 'diagonal',
				position: 'bl',
				order: 2,
				animate: [{ preset: 'draw', duration: 350, easing: 'ease-out' }],
			},
		],
	},
	W: {
		components: [
			{
				type: 'arc',
				start: 30,
				end: 150,
				order: 0,
				animate: [{ preset: 'draw', duration: 600, easing: 'ease-in-out' }],
			},
			{
				type: 'arc',
				start: 210,
				end: 330,
				order: 0,
				animate: [{ preset: 'draw', duration: 600, easing: 'ease-in-out' }],
			},
			{
				type: 'line',
				angle: 210,
				fromCenter: true,
				order: 1,
				animate: [{ preset: 'draw', duration: 400, easing: 'ease-out' }],
			},
			{
				type: 'line',
				angle: -210,
				fromCenter: true,
				order: 1,
				animate: [{ preset: 'draw', duration: 400, easing: 'ease-out' }],
			},
		],
	},
	X: {
		components: [
			{
				type: 'line',
				angle: 35,
				fromCenter: true,
				reach: 1.1,
				order: 0,
				animate: [{ preset: 'draw', duration: 500, easing: 'ease-out' }],
			},
			{
				type: 'line',
				angle: 145,
				fromCenter: true,
				reach: 1.1,
				order: 0,
				animate: [{ preset: 'draw', duration: 500, easing: 'ease-out' }],
			},
			{
				type: 'line',
				angle: -35,
				fromCenter: true,
				reach: 1.1,
				order: 1,
				animate: [{ preset: 'draw', duration: 500, easing: 'ease-out' }],
			},
			{
				type: 'line',
				angle: -145,
				fromCenter: true,
				reach: 1.1,
				order: 1,
				animate: [{ preset: 'draw', duration: 500, easing: 'ease-out' }],
			},
		],
	},
	Y: {
		components: [
			{
				type: 'arc',
				start: 100,
				end: 180,
				offset: [0, -112],
				order: 0,
				animate: [{ preset: 'draw', duration: 600, easing: 'ease-in-out', reverse: true }],
			},
			{
				type: 'arc',
				start: 180,
				end: -100,
				offset: [0, -112],
				order: 0,
				animate: [{ preset: 'draw', duration: 600, easing: 'ease-in-out' }],
			},
			/* {
				type: 'line',
				angle: 35,
				fromCenter: true,
				reach: 1.1,
				order: 0,
				animate: [{ preset: 'draw', duration: 400, easing: 'ease-out' }],
			},
			{
				type: 'line',
				angle: -35,
				fromCenter: true,
				reach: 1.1,
				order: 0,
				animate: [{ preset: 'draw', duration: 400, easing: 'ease-out' }],
			}, */
			{
				type: 'line',
				angle: 180,
				fromCenter: true,
				order: 1,
				animate: [{ preset: 'draw', duration: 400, easing: 'ease-out' }],
			},
		],
	},
	Z: {
		components: [
			{
				type: 'arc',
				start: -50,
				end: 50,
				order: 0,
				animate: [{ preset: 'draw', duration: 600, easing: 'ease-in-out' }],
			},
			{
				type: 'arc',
				start: 130,
				end: 230,
				order: 0,
				animate: [{ preset: 'draw', duration: 600, easing: 'ease-in-out' }],
			},
			{
				type: 'line',
				angle: 50,
				fromCenter: true,
				order: 1,
				animate: [{ preset: 'draw', duration: 400, easing: 'ease-out' }],
			},
			{
				type: 'line',
				angle: 230,
				fromCenter: true,
				order: 1,
				animate: [{ preset: 'draw', duration: 400, easing: 'ease-out' }],
			},
		],
	},
}
